# Site settings
title:          Rust NLP tales
description:    "Natural Language Processing and Rust"
url:            "https://guillaume-be.github.io"

# Google Analytics
google_analytics: UA-168066471-1

# Author
author:
  name:         Guillaume Becquin
  url:          https://guillaume-be.github.io
  email:        guillaume.becquin@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages
  - _posts

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag


# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
